"""
GPS C/A Gold code generator.

Implements IS-GPS-200 Table 3-Ia exactly.
Each PRN is generated by XOR-ing two 10-stage shift register (G1, G2)
outputs, with G2 tapped at PRN-specific stages to produce distinct codes.

Properties verified by unit tests:
  - Autocorrelation peak = 1023 (no noise), sidelobes ≤ 65
  - Cross-correlation between distinct PRNs ≤ 65 / 1023
  - Code period = 1023 chips exactly
"""

from __future__ import annotations

import numpy as np

from ..constants import CA_CODE_LEN

# G2 phase-select tap assignments per IS-GPS-200 Table 3-Ia
# Key: PRN number, Value: (tap_1, tap_2) — 1-indexed
G2_TAPS: dict[int, tuple[int, int]] = {
    1:  (2,  6),   2:  (3,  7),   3:  (4,  8),   4:  (5,  9),
    5:  (1,  9),   6:  (2, 10),   7:  (1,  8),   8:  (2,  9),
    9:  (3, 10),   10: (2,  3),   11: (3,  4),   12: (5,  6),
    13: (6,  7),   14: (7,  8),   15: (8,  9),   16: (9, 10),
    17: (1,  4),   18: (2,  5),   19: (3,  6),   20: (4,  7),
    21: (5,  8),   22: (6,  9),   23: (1,  3),   24: (4,  6),
    25: (5,  7),   26: (6,  8),   27: (7,  9),   28: (8, 10),
    29: (1,  6),   30: (2,  7),   31: (3,  8),   32: (4,  9),
}

# Module-level code cache: generated on first access
_CODE_CACHE: dict[int, np.ndarray] = {}


def generate_ca_code(prn: int) -> np.ndarray:
    """
    Generate 1023-chip C/A Gold code for the given PRN.

    Returned array uses NRZ (±1) convention:
      chip = 0  →  +1
      chip = 1  →  −1

    Parameters
    ----------
    prn : satellite PRN number (1–32)

    Returns
    -------
    np.ndarray shape (1023,) dtype int8, values ∈ {−1, +1}

    Raises
    ------
    ValueError : if prn is not in 1–32
    """
    if prn not in G2_TAPS:
        raise ValueError(f"PRN {prn} not supported; valid range is 1–32.")

    if prn in _CODE_CACHE:
        return _CODE_CACHE[prn]

    t1, t2 = G2_TAPS[prn]

    g1 = np.ones(10, dtype=np.int8)
    g2 = np.ones(10, dtype=np.int8)
    ca = np.empty(CA_CODE_LEN, dtype=np.int8)

    for i in range(CA_CODE_LEN):
        g1_out = int(g1[9])
        g2_out = int(g2[t1 - 1]) ^ int(g2[t2 - 1])
        ca[i]  = 1 - 2 * (g1_out ^ g2_out)   # NRZ: 0→+1, 1→−1

        # Shift G1  (feedback: taps 3, 10)
        fb1   = g1[2] ^ g1[9]
        g1[1:] = g1[:-1]
        g1[0]  = fb1

        # Shift G2  (feedback: taps 2, 3, 6, 8, 9, 10)
        fb2   = g2[1] ^ g2[2] ^ g2[5] ^ g2[7] ^ g2[8] ^ g2[9]
        g2[1:] = g2[:-1]
        g2[0]  = fb2

    _CODE_CACHE[prn] = ca
    return ca


def get_ca_code(prn: int) -> np.ndarray:
    """Return cached C/A code (generates on first call)."""
    return generate_ca_code(prn)


def clear_cache() -> None:
    """Clear the in-memory code cache (mainly for testing)."""
    _CODE_CACHE.clear()
